stages:
  - build
  - test


job_build:
  stage: build
  script:
    - echo "Building the project..."
    - matlab -nosplash -nodesktop -r "slbuild('preliminaryModel'); exit"
    - echo "Build completed successfully!"




job_test:
  stage: test
  script:
    - echo "Running tests..."
    
    # Add test commands depending on the project's testing framework (i.e., - pytest)
    - echo "Tests completed successfully!"
